(function () {
  function createInitialState() {
    return {
  activeTab: "map",
  sync: "mock",
  credits: 12430,
  energy: 8,
  energyMax: 12,
  socLevel: 4,
  rank: 128,
  keys: 3,
  cleanFragments: 0,
  gacha: { rarePity: 0, epicPity: 0, legendaryPity: 0, openCount: 0 },
  shopProducts: [],
  payments: [],
  busyProducts: new Set(),
  busyTools: new Set(),
  daemon: {
    level: 3,
    xp: 240,
    skinId: "default",
    hungerState: "fed",
    lastFedAt: null,
    autoFeedUntil: null,
  },
  content: {
    cardsById: {},
    toolsById: {},
    mapById: {},
  },
  map: [
    { id: "school",  name: "Школа",       x: 82,  y: 72,  state: "protected",   level: 4 },
    { id: "wifi",    name: "Wi-Fi узел",   x: 238, y: 72,  state: "under_attack", level: 2 },
    { id: "library", name: "Библиотека",   x: 145, y: 160, state: "protected",   level: 3 },
    { id: "media",   name: "Медиа-класс", x: 300, y: 176, state: "infected",    level: 1 },
    { id: "soc",     name: "SOC HQ",       x: 224, y: 238, state: "protected",   level: 5 },
  ],
  threats: [
    {
      id: "threat_wifi",
      title: "Пакетный шторм у Wi-Fi",
      objectId: "wifi",
      type: "DDoS",
      gameType: "packet_rain",
      game: "Packet Rain",
      expiresAt: new Date(Date.now() + 3 * 3600 * 1000).toISOString(),
      timer: "03:00:00",
      difficulty: 3,
    },
    {
      id: "threat_media",
      title: "Фишинговая волна в медиа-классе",
      objectId: "media",
      type: "Phishing",
      gameType: "packet_rain",
      game: "Packet Rain",
      expiresAt: new Date(Date.now() + 11 * 3600 * 1000).toISOString(),
      timer: "11:00:00",
      difficulty: 2,
    },
  ],
  cards: [
    {
      id: "card_001",
      name: "Фишинговая Маска",
      rarity: "common",
      level: 2,
      duplicates: 1,
      isHolo: false,
      fact: "Фишинг — кража данных через поддельные сайты. Проверяй URL перед вводом пароля.",
      weakness: "Scanner",
    },
    {
      id: "card_002",
      name: "Пакетный Шум",
      rarity: "common",
      level: 1,
      duplicates: 0,
      isHolo: false,
      fact: "DDoS-атака — тысячи устройств одновременно шлют запросы, перегружая сервер.",
      weakness: "Firewall",
    },
    {
      id: "card_003",
      name: "Вредонос-троян",
      rarity: "common",
      level: 1,
      duplicates: 0,
      isHolo: false,
      fact: "Троян маскируется под полезную программу. Никогда не запускай файлы из неизвестных источников.",
      weakness: "Analyzer",
    },
    {
      id: "card_004",
      name: "Социальный инженер",
      rarity: "rare",
      level: 1,
      duplicates: 0,
      isHolo: false,
      fact: "Социальная инженерия — манипуляция людьми для получения доступа. Не доверяй незнакомцам в сети.",
      weakness: "Deceptor",
    },
    {
      id: "card_005",
      name: "Скиммер",
      rarity: "rare",
      level: 1,
      duplicates: 0,
      isHolo: false,
      fact: "Скиммер — устройство для кражи данных карт. В банкоматах всегда проверяй картоприёмник.",
      weakness: "Scanner",
    },
    {
      id: "card_006",
      name: "QR-Мираж",
      rarity: "rare",
      level: 1,
      duplicates: 0,
      isHolo: false,
      fact: "QR-фишинг подменяет коды оплаты в кафе и магазинах. Используй только официальные QR от кассира.",
      weakness: "Scanner",
    },
    {
      id: "card_007",
      name: "Шифровальщик",
      rarity: "epic",
      level: 1,
      duplicates: 0,
      isHolo: false,
      fact: "Ransomware шифрует файлы и требует выкуп. Регулярные резервные копии — лучшая защита.",
      weakness: "Crypto",
    },
    {
      id: "card_008",
      name: "Брут-форс",
      rarity: "epic",
      level: 1,
      duplicates: 0,
      isHolo: false,
      fact: "Брутфорс перебирает пароли миллионами в секунду. Пароль из 12+ символов с буквами и цифрами — надёжен.",
      weakness: "Firewall",
    },
    {
      id: "card_009",
      name: "Нулевой День",
      rarity: "epic",
      level: 1,
      duplicates: 0,
      isHolo: false,
      fact: "Zero-day — уязвимость, о которой разработчик ещё не знает. Обновляй ПО сразу после выхода патчей.",
      weakness: "Analyzer",
    },
    {
      id: "card_010",
      name: "Wi-Fi Phantom",
      rarity: "legendary",
      level: 1,
      duplicates: 0,
      isHolo: false,
      fact: "Evil Twin — поддельная Wi-Fi точка с именем café_free. Подключившись, хакер видит весь твой трафик.",
      weakness: "Scanner",
    },
    {
      id: "card_011",
      name: "Дипфейк-агент",
      rarity: "legendary",
      level: 1,
      duplicates: 0,
      isHolo: false,
      fact: "Дипфейк создаёт убедительные видео и голос. Верифицируй звонки от «начальника» по другому каналу.",
      weakness: "Analyzer",
    },
  ],
  tools: [
    { id: "tool_scanner",  name: "Pulse Scanner",   className: "Scanner",  level: 2, equipped: true,  slotIndex: 1, description: "Подсвечивает опасные пакеты в мини-игре." },
    { id: "tool_firewall", name: "Glass Firewall",  className: "Firewall", level: 1, equipped: true,  slotIndex: 2, description: "Поглощает ошибки без штрафа." },
    { id: "tool_crypto",   name: "Shift Dial",      className: "Crypto",   level: 1, equipped: false, slotIndex: null, description: "Даёт подсказки при расшифровке." },
    { id: "tool_analyzer", name: "Deep Analyzer",   className: "Analyzer", level: 1, equipped: false, slotIndex: null, description: "Добавляет время в мини-игре." },
  ],
    };
  }

  window.ZDNETMockState = { createInitialState };
}());
